### ISSUE TITLE
question: day_of_year why not return u16?

### ISSUE THREAD

**Issue by TCeason** [BurntSushi/jiff#158] opened 2024-11-06 03:07 UTC
```rust
#[inline]
    pub fn day_of_year(self) -> i16 {
        type DayOfYear = ri16<1, 366>;

        let days = C(1) + self.since_days_ranged(self.first_of_year());
        DayOfYear::rfrom(days).get()
    }
```

Maybe other function can also return unsigned number.

**Comment by BurntSushi** [comment] 2024-11-06 03:13
Duplicate of #35, #102.

**Closed by BurntSushi** 2024-11-06 03:13 UTC
